# This is a basic workflow to help you get started with Actions

name: second workflow

# Controls when the workflow will run
on: workflow_dispatch

jobs:
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: multiple line shell command
        run: | 
            echo "First output"
            echo "Second output"
